// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $admin_middleware from "./routes/admin/_middleware.ts";
import * as $admin_create from "./routes/admin/create.tsx";
import * as $admin_events from "./routes/admin/events.tsx";
import * as $admin_index from "./routes/admin/index.tsx";
import * as $admin_logout from "./routes/admin/logout.tsx";
import * as $api_events from "./routes/api/events.ts";
import * as $api_events_eventId_tickets_ticketId_ from "./routes/api/events/[eventId]/tickets/[ticketId].ts";
import * as $api_events_eventId_watch from "./routes/api/events/[eventId]/watch.ts";
import * as $api_participants_eventId_ticketNumber_ from "./routes/api/participants/[eventId]/[ticketNumber].ts";
import * as $event_id_created from "./routes/event/[id]/created.tsx";
import * as $event_id_export from "./routes/event/[id]/export.ts";
import * as $event_id_index from "./routes/event/[id]/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $CategoryManager from "./islands/CategoryManager.tsx";
import * as $CategorySelector from "./islands/CategorySelector.tsx";
import * as $DeleteEventButton from "./islands/DeleteEventButton.tsx";
import * as $EventActions from "./islands/EventActions.tsx";
import * as $EventNotFoundPage from "./islands/EventNotFoundPage.tsx";
import * as $EventPage from "./islands/EventPage.tsx";
import * as $ParticipantsTable from "./islands/ParticipantsTable.tsx";
import * as $RealtimeParticipants from "./islands/RealtimeParticipants.tsx";
import * as $RealtimeUpdater from "./islands/RealtimeUpdater.tsx";
import * as $ThemeSwitcher from "./islands/ThemeSwitcher.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/admin/_middleware.ts": $admin_middleware,
    "./routes/admin/create.tsx": $admin_create,
    "./routes/admin/events.tsx": $admin_events,
    "./routes/admin/index.tsx": $admin_index,
    "./routes/admin/logout.tsx": $admin_logout,
    "./routes/api/events.ts": $api_events,
    "./routes/api/events/[eventId]/tickets/[ticketId].ts":
      $api_events_eventId_tickets_ticketId_,
    "./routes/api/events/[eventId]/watch.ts": $api_events_eventId_watch,
    "./routes/api/participants/[eventId]/[ticketNumber].ts":
      $api_participants_eventId_ticketNumber_,
    "./routes/event/[id]/created.tsx": $event_id_created,
    "./routes/event/[id]/export.ts": $event_id_export,
    "./routes/event/[id]/index.tsx": $event_id_index,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/CategoryManager.tsx": $CategoryManager,
    "./islands/CategorySelector.tsx": $CategorySelector,
    "./islands/DeleteEventButton.tsx": $DeleteEventButton,
    "./islands/EventActions.tsx": $EventActions,
    "./islands/EventNotFoundPage.tsx": $EventNotFoundPage,
    "./islands/EventPage.tsx": $EventPage,
    "./islands/ParticipantsTable.tsx": $ParticipantsTable,
    "./islands/RealtimeParticipants.tsx": $RealtimeParticipants,
    "./islands/RealtimeUpdater.tsx": $RealtimeUpdater,
    "./islands/ThemeSwitcher.tsx": $ThemeSwitcher,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
